export enum EN_ExceptionMessage{
    AUTH_FIND_USER = '\'شماره تلفن قبلاً ثبت شده است.',
    AUTH_NOT_FIND_USER_BY_MOBILE = "کاربری با ابن شماره تلفن یافت نشد.",
    AUTH_INCORRECT_PASSWORD="رمز عبور اشتباه است.",
    AUTH_EXPIRE_CODE="کد تایید نادرست یا منقضی شده است.",
    AUTH_NOT_HAVING="رمز عبوری برای حساب کاربری شما اعمال نشده است با رمز عبور یکبار مصرف اقدام به ورود کنید.",
    USER_NOT_FOUND = 'کاربر با این شناسه پیدا نشد.',
    LESSOR_NOT_FOUND = 'اجاره دهنده ای با این شناسه پیدا نشد.',
    NOT_FOUND = 'اطلاعات یافت نشد.',
    USER_REPETITIVE_USERNAME = 'این نام کاربری قبلا ثبت شده است.',
    AUTH_VALID_TOKEN_NOT_SENT = 'توکن معتبر ارسال نشده است.',
    AUTH_NOT_ALLOWED_CALL_SERVICE = 'شما اجازه فراخوانی این سرویس را ندارید.',
    AUTH_TOKEN_NOT_VALID_HAS_EXPIRED = 'توکن معتبر نیست یا منقضی شده است.',
    POST_EXISTS = 'این پست قبلا ثبت شده است.',
    CATEGORY_NOT_FOUND = 'دسته بندی با این شناسه یافت نشد.',
    LESSOR_UNDER_REVIEW = "کاربر گرامی شما یک درخواست به عنوان اجاره دهنده در وضعیت درحال بررسی دارید.",
    LESSOR_CONFIRMED = "کاربر گرامی حساب کاربری شما به عنوان اجاره دهنده فعال می باشد.",
    CAR_YEAR_IS_REQUIRED = 'خودرو هایی با سال ساخت بالای 5 سال ملزم به آپلود معاینه فنی هستند.',
    CAR_NOT_FOUND = 'خودرویی با این شناسه یافت نشد.',
    CAR_NOT_UNDER_REVIEW = 'خودرو مورد نظر جهت تغیر وضعیت باید در وضعیت در حال بررسی باشد.',
    POST_NOT_FOUND = 'نوشته ای یافت نشد.',
    ORDERS_CAR_ID_UNIQUE= "کاربر گرامی درخواست شما برای خودروی  دیگری ثبت شده است و مورد بررسی است.",
    ORDERS_UNIQUE= "کاربر گرامی درخواست شما ثبت شده و درحال بررسی می باشد.",

}
